#!/bin/bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}" || exit 1

../vendor/bin/infection \
  --min-msi=80 \
  --configuration=inflection.json \
  --test-framework-options='./src/Test/BackwardCompatibleTestSuite.php' \
  --threads=16 \
  --log-verbosity=2 \
  --only-covered
